//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot contain space..
        /// </summary>
        public static string CannotContainSpace {
            get {
                return ResourceManager.GetString("CannotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (USA).
        /// </summary>
        public static string EnglishUS {
            get {
                return ResourceManager.GetString("EnglishUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB or TMDB ID already registered.
        /// </summary>
        public static string ImdbOrTmdbIdAlreadyRegistered {
            get {
                return ResourceManager.GetString("ImdbOrTmdbIdAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size.
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language code must be an ISO 690 code.
        /// </summary>
        public static string LanguageCodeMustIso {
            get {
                return ResourceManager.GetString("LanguageCodeMustIso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size exceeded.
        /// </summary>
        public static string MaximumSizeExceeded {
            get {
                return ResourceManager.GetString("MaximumSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than zero.
        /// </summary>
        public static string MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain &apos;Synopsis&apos; at the end.
        /// </summary>
        public static string MustContainSynopsisAtTheEnd {
            get {
                return ResourceManager.GetString("MustContainSynopsisAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not contain &apos;Synopsis&apos; at the end.
        /// </summary>
        public static string MustNotContainSynopsisAtTheEnd {
            get {
                return ResourceManager.GetString("MustNotContainSynopsisAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not created.
        /// </summary>
        public static string NotCreated {
            get {
                return ResourceManager.GetString("NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred.
        /// </summary>
        public static string OneOrMoreValidationErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string PortuguesBR {
            get {
                return ResourceManager.GetString("PortuguesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should just be letters without accents.
        /// </summary>
        public static string ShouldBeLettersWithoutAccents {
            get {
                return ResourceManager.GetString("ShouldBeLettersWithoutAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should just be letters without accents or numbers.
        /// </summary>
        public static string ShouldBeLettersWithoutAccentsOrNumbers {
            get {
                return ResourceManager.GetString("ShouldBeLettersWithoutAccentsOrNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some resource is duplicated.
        /// </summary>
        public static string SomeResourceIsDuplicated {
            get {
                return ResourceManager.GetString("SomeResourceIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StardateFrom must be a value less than or equal to StardateTo.
        /// </summary>
        public static string StardateFromLessThanOrEqualStardateTo {
            get {
                return ResourceManager.GetString("StardateFromLessThanOrEqualStardateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero.
        /// </summary>
        public static string ValueGreaterThanZero {
            get {
                return ResourceManager.GetString("ValueGreaterThanZero", resourceCulture);
            }
        }
    }
}
