IF NOT EXISTS(SELECT TOP 1 1 FROM Country)
BEGIN
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Afghanistan', 'AF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Albania', 'AL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Algeria', 'DZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('American Samoa', 'AS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Andorra', 'AD');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Angola', 'AO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Anguilla', 'AI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Antarctica', 'AQ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Antigua and Barbuda', 'AG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Argentina', 'AR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Armenia', 'AM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Aruba', 'AW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Australia', 'AU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Austria', 'AT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Azerbaijan', 'AZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bahamas', 'BS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bahrain', 'BH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bangladesh', 'BD');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Barbados', 'BB');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Belarus', 'BY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Belgium', 'BE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Belize', 'BZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Benin', 'BJ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bermuda', 'BM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bhutan', 'BT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bosnia and Herzegovina', 'BA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Botswana', 'BW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bouvet Island', 'BV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Brazil', 'BR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('British Indian Ocean Territory', 'IO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Brunei Darussalam', 'BN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Bulgaria', 'BG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Burkina Faso', 'BF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Burundi', 'BI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cambodia', 'KH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cameroon', 'CM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Canada', 'CA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cape Verde', 'CV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cayman Islands', 'KY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Central African Republic', 'CF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Chad', 'TD');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Chile', 'CL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('China', 'CN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Christmas Island', 'CX');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cocos (Keeling) Islands', 'CC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Colombia', 'CO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Comoros', 'KM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Congo', 'CG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cook Islands', 'CK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Costa Rica', 'CR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Croatia', 'HR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cuba', 'CU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Cyprus', 'CY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Czech Republic', 'CZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Denmark', 'DK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Djibouti', 'DJ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Dominica', 'DM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Dominican Republic', 'DO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Ecuador', 'EC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Egypt', 'EG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('El Salvador', 'SV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Equatorial Guinea', 'GQ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Eritrea', 'ER');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Estonia', 'EE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Ethiopia', 'ET');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Falkland Islands (Malvinas)' ,'FK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Faroe Islands', 'FO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Fiji', 'FJ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Finland', 'FI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('France', 'FR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('French Guiana', 'GF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('French Polynesia', 'PF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('French Southern Territories', 'TF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Gabon', 'GA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Gambia', 'GM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Georgia', 'GE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Germany', 'DE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Ghana', 'GH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Gibraltar', 'GI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Greece', 'GR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Greenland', 'GL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Grenada', 'GD');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guadeloupe', 'GP');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guam', 'GU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guatemala', 'GT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guernsey', 'GG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guinea', 'GN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guinea-Bissau', 'GW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Guyana', 'GY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Haiti', 'HT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Heard Island and McDonald Islands', 'HM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Holy See (Vatican City State)' ,'VA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Honduras', 'HN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Hong Kong', 'HK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Hungary', 'HU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Iceland', 'IS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('India', 'IN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Indonesia', 'ID');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Iran', 'IR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Iraq', 'IQ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Ireland', 'IE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Isle of Man', 'IM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Israel', 'IL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Italy', 'IT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Jamaica', 'JM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Japan', 'JP');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Jersey', 'JE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Jordan', 'JO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Kazakhstan', 'KZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Kenya', 'KE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Kiribati', 'KI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Kuwait', 'KW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Kyrgyzstan', 'KG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Lao Peoples Democratic Republic', 'LA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Latvia', 'LV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Lebanon', 'LB');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Lesotho', 'LS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Liberia', 'LR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Libya', 'LY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Liechtenstein', 'LI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Lithuania', 'LT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Luxembourg', 'LU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Macao', 'MO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Madagascar', 'MG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Malawi', 'MW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Malaysia', 'MY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Maldives', 'MV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mali', 'ML');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Malta', 'MT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Marshall Islands', 'MH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Martinique', 'MQ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mauritania', 'MR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mauritius', 'MU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mayotte', 'YT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mexico', 'MX');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Monaco', 'MC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mongolia', 'MN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Montenegro', 'ME');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Montserrat', 'MS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Morocco', 'MA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Mozambique', 'MZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Myanmar', 'MM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Namibia', 'NA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Nauru', 'NR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Nepal', 'NP');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Netherlands', 'NL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('New Caledonia', 'NC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('New Zealand', 'NZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Nicaragua', 'NI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Niger', 'NE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Nigeria', 'NG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Niue', 'NU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Norfolk Island', 'NF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Northern Mariana Islands', 'MP');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Norway', 'NO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Oman', 'OM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Pakistan', 'PK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Palau', 'PW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Panama', 'PA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Papua New Guinea', 'PG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Paraguay', 'PY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Peru', 'PE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Philippines', 'PH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Pitcairn', 'PN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Poland', 'PL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Portugal', 'PT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Puerto Rico', 'PR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Qatar', 'QA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Romania', 'RO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Russian Federation', 'RU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Rwanda', 'RW');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saint Kitts and Nevis', 'KN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saint Lucia', 'LC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saint Martin (French part)' ,'MF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saint Pierre and Miquelon', 'PM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saint Vincent and the Grenadines', 'VC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Samoa', 'WS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('San Marino', 'SM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sao Tome and Principe', 'ST');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Saudi Arabia', 'SA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Senegal', 'SN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Serbia', 'RS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Seychelles', 'SC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sierra Leone', 'SL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Singapore', 'SG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sint Maarten (Dutch part)' ,'SX');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Slovakia', 'SK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Slovenia', 'SI');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Solomon Islands', 'SB');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Somalia', 'SO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('South Africa', 'ZA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('South Georgia and the South Sandwich Islands', 'GS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('South Sudan', 'SS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Spain', 'ES');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sri Lanka', 'LK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('State of Palestine', 'PS');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sudan', 'SD');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Suriname', 'SR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Svalbard and Jan Mayen', 'SJ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Swaziland', 'SZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Sweden', 'SE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Switzerland', 'CH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Syrian Arab Republic', 'SY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Tajikistan', 'TJ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Thailand', 'TH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Timor-Leste', 'TL');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Togo', 'TG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Tokelau', 'TK');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Tonga', 'TO');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Trinidad and Tobago', 'TT');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Tunisia', 'TN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Turkey', 'TR');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Turkmenistan', 'TM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Turks and Caicos Islands', 'TC');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Tuvalu', 'TV');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Uganda', 'UG');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Ukraine', 'UA');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('United Arab Emirates', 'AE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('United Kingdom', 'GB');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('United States', 'US');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('United States Minor Outlying Islands', 'UM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Uruguay', 'UY');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Uzbekistan', 'UZ');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Vanuatu', 'VU');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Viet Nam', 'VN');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Wallis and Futuna', 'WF');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Western Sahara', 'EH');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Yemen', 'YE');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Zambia', 'ZM');
	INSERT INTO Country ([ResourceName], ISO) VALUES ('Zimbabwe', 'ZW');
END