//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot contain space..
        /// </summary>
        public static string CannotContainSpace {
            get {
                return ResourceManager.GetString("CannotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate episode number.
        /// </summary>
        public static string DuplicateEpisodeNumber {
            get {
                return ResourceManager.GetString("DuplicateEpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate resource.
        /// </summary>
        public static string DuplicateResource {
            get {
                return ResourceManager.GetString("DuplicateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (USA).
        /// </summary>
        public static string EnglishUS {
            get {
                return ResourceManager.GetString("EnglishUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode already registered.
        /// </summary>
        public static string EpisodeAlreadyRegistered {
            get {
                return ResourceManager.GetString("EpisodeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB or TMDB ID already registered.
        /// </summary>
        public static string ImdbOrTmdbIdAlreadyRegistered {
            get {
                return ResourceManager.GetString("ImdbOrTmdbIdAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length.
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It cannot be a future date.
        /// </summary>
        public static string ItCannotBeaFutureDate {
            get {
                return ResourceManager.GetString("ItCannotBeaFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language code must be an ISO 690 code.
        /// </summary>
        public static string LanguageCodeMustIso {
            get {
                return ResourceManager.GetString("LanguageCodeMustIso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length exceeded.
        /// </summary>
        public static string MaximumLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size exceeded.
        /// </summary>
        public static string MaximumSizeExceeded {
            get {
                return ResourceManager.GetString("MaximumSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than zero.
        /// </summary>
        public static string MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain &apos;Synopsis&apos; at the end.
        /// </summary>
        public static string MustContainSynopsisAtTheEnd {
            get {
                return ResourceManager.GetString("MustContainSynopsisAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not contain &apos;Synopsis&apos; at the end.
        /// </summary>
        public static string MustNotContainSynopsisAtTheEnd {
            get {
                return ResourceManager.GetString("MustNotContainSynopsisAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must start with the series abbreviation.
        /// </summary>
        public static string MustStartWithTheSeriesAbbreviation {
            get {
                return ResourceManager.GetString("MustStartWithTheSeriesAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not created.
        /// </summary>
        public static string NotCreated {
            get {
                return ResourceManager.GetString("NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred.
        /// </summary>
        public static string OneOrMoreValidationErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreValidationErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        public static string OriginalLanguage {
            get {
                return ResourceManager.GetString("OriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Name.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        public static string PortuguesBR {
            get {
                return ResourceManager.GetString("PortuguesBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realease Date.
        /// </summary>
        public static string RealeaseDate {
            get {
                return ResourceManager.GetString("RealeaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season already registered.
        /// </summary>
        public static string SeasonAlreadyRegistered {
            get {
                return ResourceManager.GetString("SeasonAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season ID.
        /// </summary>
        public static string SeasonID {
            get {
                return ResourceManager.GetString("SeasonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie ID.
        /// </summary>
        public static string SerieID {
            get {
                return ResourceManager.GetString("SerieID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should just be letters without accents.
        /// </summary>
        public static string ShouldBeLettersWithoutAccents {
            get {
                return ResourceManager.GetString("ShouldBeLettersWithoutAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should just be letters without accents or numbers.
        /// </summary>
        public static string ShouldBeLettersWithoutAccentsOrNumbers {
            get {
                return ResourceManager.GetString("ShouldBeLettersWithoutAccentsOrNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some resource is duplicated.
        /// </summary>
        public static string SomeResourceIsDuplicated {
            get {
                return ResourceManager.GetString("SomeResourceIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station stations.
        /// </summary>
        public static string SpaceStation {
            get {
                return ResourceManager.GetString("SpaceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stardate From.
        /// </summary>
        public static string StardateFrom {
            get {
                return ResourceManager.GetString("StardateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StardateFrom must be a value less than or equal to StardateTo.
        /// </summary>
        public static string StardateFromLessThanOrEqualStardateTo {
            get {
                return ResourceManager.GetString("StardateFromLessThanOrEqualStardateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stardate To.
        /// </summary>
        public static string StardateTo {
            get {
                return ResourceManager.GetString("StardateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synopsis.
        /// </summary>
        public static string Synopsis {
            get {
                return ResourceManager.GetString("Synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Name.
        /// </summary>
        public static string TranslatedName {
            get {
                return ResourceManager.GetString("TranslatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero.
        /// </summary>
        public static string ValueGreaterThanZero {
            get {
                return ResourceManager.GetString("ValueGreaterThanZero", resourceCulture);
            }
        }
    }
}
