//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlacesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlacesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.PlacesResource", typeof(PlacesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Space Nine.
        /// </summary>
        public static string DeepSpaceNine {
            get {
                return ResourceManager.GetString("DeepSpaceNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet.
        /// </summary>
        public static string Planet {
            get {
                return ResourceManager.GetString("Planet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant Alpha.
        /// </summary>
        public static string QuadrantAlphaResource {
            get {
                return ResourceManager.GetString("QuadrantAlphaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant Beta.
        /// </summary>
        public static string QuadrantBetaResource {
            get {
                return ResourceManager.GetString("QuadrantBetaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant Delta.
        /// </summary>
        public static string QuadrantDeltaResource {
            get {
                return ResourceManager.GetString("QuadrantDeltaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant Gamma.
        /// </summary>
        public static string QuadrantGammaResource {
            get {
                return ResourceManager.GetString("QuadrantGammaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Francisco.
        /// </summary>
        public static string SanFrancisco {
            get {
                return ResourceManager.GetString("SanFrancisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Station.
        /// </summary>
        public static string SpaceStation {
            get {
                return ResourceManager.GetString("SpaceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
    }
}
