//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleSynopsis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleSynopsis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.TitleSynopsis", typeof(TitleSynopsis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek: The Animated Series.
        /// </summary>
        public static string AnimatedSeries {
            get {
                return ResourceManager.GetString("AnimatedSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The further adventures of Captain James T. Kirk and the crew of the USS Enterprise, as they explore the galaxy and defend the United Federation of Planets..
        /// </summary>
        public static string AnimatedSeriesSynopsis {
            get {
                return ResourceManager.GetString("AnimatedSeriesSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek: Deep Space Nine.
        /// </summary>
        public static string DeepSpaceNine {
            get {
                return ResourceManager.GetString("DeepSpaceNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissary.
        /// </summary>
        public static string ds9Emissary {
            get {
                return ResourceManager.GetString("ds9Emissary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the troubled Commander Sisko takes command of a surrendered space station, he learns that it borders a unique stable wormhole..
        /// </summary>
        public static string ds9EmissarySynopsis {
            get {
                return ResourceManager.GetString("ds9EmissarySynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek: The Motion Picture.
        /// </summary>
        public static string MotionPicture {
            get {
                return ResourceManager.GetString("MotionPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an alien spacecraft of enormous power is spotted approaching Earth, Admiral James T. Kirk resumes command of the overhauled USS Enterprise in order to intercept it..
        /// </summary>
        public static string MotionPictureSynopsis {
            get {
                return ResourceManager.GetString("MotionPictureSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek: The Next Generation.
        /// </summary>
        public static string NextGeneration {
            get {
                return ResourceManager.GetString("NextGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set almost 100 years after Captain Kirk&apos;s 5-year mission, a new generation of Starfleet officers sets off in the U.S.S. Enterprise-D on its own mission to go where no one has gone before..
        /// </summary>
        public static string NextGenerationSynopsis {
            get {
                return ResourceManager.GetString("NextGenerationSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek.
        /// </summary>
        public static string OriginalSeries {
            get {
                return ResourceManager.GetString("OriginalSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the 23rd Century, Captain James T. Kirk and the crew of the U.S.S. Enterprise explore the galaxy and defend the United Federation of Planets..
        /// </summary>
        public static string OriginalSeriesSynopsis {
            get {
                return ResourceManager.GetString("OriginalSeriesSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter at Farpoint.
        /// </summary>
        public static string tngEncounteratFarpoint {
            get {
                return ResourceManager.GetString("tngEncounteratFarpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the maiden mission of the U.S.S. Enterprise (NCC-1701-D), an omnipotent being known as Q challenges the crew to discover the secret of a mysterious base in an advanced and civilized fashion..
        /// </summary>
        public static string tngEncounteratFarpointSynopsis {
            get {
                return ResourceManager.GetString("tngEncounteratFarpointSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Trek II: The Wrath of Khan.
        /// </summary>
        public static string WrathOfKhan {
            get {
                return ResourceManager.GetString("WrathOfKhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the assistance of the Enterprise crew, Admiral Kirk must stop an old nemesis, Khan Noonien Singh, from using the life-generating Genesis Device as the ultimate weapon..
        /// </summary>
        public static string WrathOfKhanSynopsis {
            get {
                return ResourceManager.GetString("WrathOfKhanSynopsis", resourceCulture);
            }
        }
    }
}
